# Generated by Django 3.2.6 on 2021-09-01 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('nome_aluno', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('data_envio', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
