# Generated by Django 3.2.6 on 2021-09-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatorio',
            old_name='descricao',
            new_name='descricao_status',
        ),
    ]
